// src/app/api/admin/create-personel-user/route.ts
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { createSupabaseServiceClient } from '@/lib/supabase/service';
import { normalizeAllowedAdminPanels, normalizeInternalNotificationPreferences } from '@/lib/admin/panel-access';
import { sendPortalWelcomeEmail } from '@/lib/email';
import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';

function getSiteUrl(request: Request): string {
  if (process.env.NEXT_PUBLIC_SITE_URL) {
    return process.env.NEXT_PUBLIC_SITE_URL.replace(/\/$/, '');
  }
  const forwardedHost = request.headers.get('x-forwarded-host');
  const forwardedProto = request.headers.get('x-forwarded-proto') || 'https';
  if (forwardedHost && !forwardedHost.includes('localhost') && !forwardedHost.includes('127.0.0.1')) {
    return `${forwardedProto}://${forwardedHost}`;
  }
  const { origin } = new URL(request.url);
  if (!origin.includes('localhost') && !origin.includes('127.0.0.1')) {
    return origin;
  }
  return 'https://elysonsweets.de';
}

const VALID_ROLES = ['Yönetici', 'Personel', 'Müşteri', 'Alt Bayi'] as const;
type ValidRole = (typeof VALID_ROLES)[number];

function generateFriendlyPassword(): string {
  const num = Math.floor(1000 + Math.random() * 9000);
  return `Sweet${num}!`;
}

export async function POST(request: Request) {
  const cookieStore = await cookies();
  const supabase = await createSupabaseServerClient(cookieStore);

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return new NextResponse(JSON.stringify({ error: 'Yetkiniz yok' }), { status: 401 });
  }

  const { data: profile } = await supabase.from('profiller').select('rol').eq('id', user.id).single();
  if (profile?.rol !== 'Yönetici') {
    return new NextResponse(JSON.stringify({ error: 'Bu işlemi yapmaya sadece yöneticiler yetkilidir' }), { status: 403 });
  }

  let payload: {
    email?: string;
    password?: string;
    tam_ad?: string | null;
    rol?: string;
    allowedPanels?: string[];
    notificationPreferences?: Record<string, boolean> | null;
    firma_id?: string | null;
    sendInviteEmail?: boolean;
    locale?: string;
  } = {};
  try {
    payload = await request.json();
  } catch {
    return new NextResponse(JSON.stringify({ error: 'Geçersiz istek gövdesi' }), { status: 400 });
  }

  const email = payload.email?.trim().toLowerCase();
  if (!email) {
    return new NextResponse(JSON.stringify({ error: 'E-posta adresi zorunludur.' }), { status: 400 });
  }

  const explicitPassword = typeof payload.password === 'string' && payload.password.trim().length > 0
    ? payload.password.trim()
    : null;
  const tam_ad = payload.tam_ad?.trim() || null;
  const rol = VALID_ROLES.includes((payload.rol || 'Personel') as ValidRole)
    ? (payload.rol as ValidRole)
    : 'Personel';
  const isPortalRole = rol === 'Müşteri' || rol === 'Alt Bayi';
  const firmaId = payload.firma_id?.trim() || null;
  const sendInviteEmail = payload.sendInviteEmail === true;
  const locale = isPortalRole ? (payload.locale || 'de') : (payload.locale || 'tr');
  const siteUrl = getSiteUrl(request);
  const redirectTo = `${siteUrl}/${locale}/auth/reset-password`;
  const allowedPanels = isPortalRole ? [] : normalizeAllowedAdminPanels(payload.allowedPanels);
  const notificationPreferences = isPortalRole ? null : normalizeInternalNotificationPreferences(payload.notificationPreferences);

  if (isPortalRole && !firmaId) {
    return new NextResponse(JSON.stringify({ error: 'Müşteri veya alt bayi kullanıcıları mevcut bir firmaya bağlanmalıdır.' }), { status: 400 });
  }

  // Determine password to use
  let finalPassword = explicitPassword;
  let isAutoGeneratedPassword = false;
  if (!finalPassword) {
    if (!sendInviteEmail) {
      finalPassword = generateFriendlyPassword();
      isAutoGeneratedPassword = true;
    } else {
      finalPassword = `${crypto.randomUUID().slice(0, 12)}Aa1!`;
    }
  }

  const supabaseAdmin = createSupabaseServiceClient();
  const userMetadata = {
    tam_ad: tam_ad || null,
    allowed_admin_panels: allowedPanels,
    ...(notificationPreferences ? { internal_notification_preferences: notificationPreferences } : {}),
  };

  let authUser: { id: string } | null = null;
  let usedExistingUser = false;

  // 1. Try to create the user directly with confirmed email so they are immediately active
  const { data: created, error: createError } = await supabaseAdmin.auth.admin.createUser({
    email,
    password: finalPassword,
    email_confirm: true,
    user_metadata: userMetadata,
  });

  authUser = created?.user ? { id: created.user.id } : null;

  if (createError || !authUser) {
    const normalizedError = String(createError?.message || '').toLowerCase();
    const isExistingUserError = normalizedError.includes('already') || normalizedError.includes('registered') || normalizedError.includes('exists');

    if (!isExistingUserError) {
      console.error('Kullanıcı oluşturma hatası (auth):', createError);
      return new NextResponse(JSON.stringify({ error: createError?.message || 'Kullanıcı oluşturulamadı' }), { status: 500 });
    }

    // Existing user: find user ID
    const { data: authUsersData, error: listUsersError } = await supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 1000 });
    if (listUsersError) {
      console.error('Mevcut auth kullanıcısı alınamadı:', listUsersError);
      return new NextResponse(JSON.stringify({ error: listUsersError.message }), { status: 500 });
    }

    const existingUser = authUsersData.users.find((item) => (item.email ?? '').trim().toLowerCase() === email);
    if (!existingUser) {
      console.error('Mevcut kullanıcı bulunamadı:', createError);
      return new NextResponse(JSON.stringify({ error: createError?.message || 'Kullanıcı oluşturulamadı' }), { status: 500 });
    }

    usedExistingUser = true;
    authUser = { id: existingUser.id };

    // Update password if explicit password was provided or password was auto-generated
    if (explicitPassword || isAutoGeneratedPassword) {
      const { data: updatedAuthUser, error: updateAuthError } = await supabaseAdmin.auth.admin.updateUserById(existingUser.id, {
        password: finalPassword,
        email_confirm: true,
        user_metadata: {
          ...(existingUser.user_metadata || {}),
          ...userMetadata,
        },
      });

      if (updateAuthError) {
        console.error('Mevcut kullanıcının şifresi güncellenemedi:', updateAuthError);
      } else if (updatedAuthUser?.user) {
        authUser = { id: updatedAuthUser.user.id };
      }
    }
  }

  // 2. Upsert profile in profiller table
  const { error: profileError } = await supabaseAdmin.from('profiller').upsert({
    id: authUser.id,
    rol: rol as never,
    tam_ad: tam_ad || null,
    firma_id: firmaId,
  });

  if (profileError) {
    console.error('Kullanıcı oluşturma hatası (profil):', profileError);
    return new NextResponse(JSON.stringify({ error: profileError.message }), { status: 500 });
  }

  // 3. Update firma status in firmalar table
  if (isPortalRole && firmaId) {
    try {
      const { data: currentFirma } = await supabaseAdmin.from('firmalar').select('status').eq('id', firmaId).single();
      const currentStatus = String(currentFirma?.status || '').toUpperCase();
      const updatePayload: Record<string, any> = {};

      if (rol === 'Alt Bayi') {
        updatePayload.status = 'ALT BAYİ';
        updatePayload.sahip_id = authUser.id;
      } else if (currentStatus === 'ADAY' || !currentFirma?.status) {
        updatePayload.status = 'MÜŞTERİ';
      }

      if (Object.keys(updatePayload).length > 0) {
        await supabaseAdmin.from('firmalar').update(updatePayload).eq('id', firmaId);
      }
    } catch (err) {
      console.error('Firma durumu güncellenirken hata:', err);
    }
  }

  // 4. Generate recovery / reset action link (direct link to live website)
  let actionLink: string | null = null;
  try {
    const { data: linkData, error: linkErr } = await supabaseAdmin.auth.admin.generateLink({
      type: 'recovery',
      email,
      options: { redirectTo },
    });
    if (!linkErr && linkData?.properties) {
      if (linkData.properties.hashed_token) {
        actionLink = `${siteUrl}/${locale}/auth/reset-password?token_hash=${linkData.properties.hashed_token}&type=recovery`;
      } else if (linkData.properties.action_link) {
        actionLink = linkData.properties.action_link;
      }
    }
  } catch (err) {
    console.error('generateLink hatası:', err);
  }

  // 5. Send branded ElysonSweets email if requested
  if (sendInviteEmail) {
    try {
      let firmaUnvan: string | null = null;
      if (firmaId) {
        const { data: f } = await supabaseAdmin.from('firmalar').select('unvan').eq('id', firmaId).single();
        firmaUnvan = f?.unvan || null;
      }

      await sendPortalWelcomeEmail({
        to: email,
        recipientName: tam_ad,
        firmName: firmaUnvan,
        tempPassword: explicitPassword || isAutoGeneratedPassword ? finalPassword : null,
        actionLink,
        loginUrl: `${siteUrl}/${locale}/login`,
        locale,
      });
    } catch (err) {
      console.warn('ElysonSweets portal e-posta gönderim hatası:', err);
    }
  }

  const message = usedExistingUser
    ? explicitPassword || isAutoGeneratedPassword
      ? 'Kullanıcı hesabı güncellendi ve şifre belirlendi.'
      : 'Kullanıcı hesabı güncellendi.'
    : 'Portal kullanıcısı başarıyla oluşturuldu.';

  return NextResponse.json({
    success: true,
    message,
    userId: authUser.id,
    email,
    tempPassword: explicitPassword || isAutoGeneratedPassword ? finalPassword : null,
    actionLink,
    loginUrl: `${siteUrl}/${locale}/login`,
    rol,
    allowedPanels,
    notificationPreferences,
    firma_id: firmaId,
    inviteSent: sendInviteEmail,
    loginReady: Boolean(explicitPassword || isAutoGeneratedPassword),
  });
}
